# Generated by Django 4.1.5 on 2023-01-13 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_categories_alter_blogs_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 13, 18, 20, 56, 551553), null=None),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 13, 18, 20, 56, 551553), null=None),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 13, 18, 20, 56, 552508), null=None),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 13, 18, 20, 56, 552508), null=None),
        ),
    ]
