# Generated by Django 4.1.5 on 2023-10-10 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_created_at_alter_blogs_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 10, 10, 21, 3, 27, 328777), null=None),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 10, 10, 21, 3, 27, 328777), null=None),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 10, 10, 21, 3, 27, 329813), null=None),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 10, 10, 21, 3, 27, 330791), null=None),
        ),
    ]
